feat: adapt to type of combo
meixg/amis2schema pull request #10
Opened 2022-12-01 06:23 UTC by enthss

2022-12-01 06:27 UTC, meixg requested changes

2022-12-01 06:27 UTC, meixg commented on src/index.ts
> +                return this.compileFormOrCombo(control, control.type, control.multiple);
只传 control 就可以了

2022-12-01 06:27 UTC, enthss commented on src/index.ts
> +                return this.compileFormOrCombo(control, control.type, control.multiple);
好的~

2022-12-02 09:15 UTC, meixg approved these changes

2022-12-02 09:15 UTC, merged